print("contact form")
name=input("enter you name ")
age=int(input("enter your age "))
course=input("enter your course ")
contact=int(input("enter your phone number "))
print("the name you had entered is ",name)
print("the age you had entered is ",age)
print("the course you had entered is ",course)
print("contact you had entered is ",contact)
print("CONFIRMATION")
confirmation=input("the above mentioned information is true or false ")
